
//import AppPackage.AnimationClass;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import matlabcontrol.MatlabInvocationException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jamie
 */
public class IntroGUI extends javax.swing.JFrame {
     String carrier; 
     public static String email; 

    /**
     * Creates new form IntroGUI
     */
    public IntroGUI() {
        initComponents();
        getContentPane().setBackground(Color.gray);
        //AnimationClass action = new AnimationClass();
        //action.jLabelYDown(0,50,500,1,helloUser);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 50), new java.awt.Dimension(120, 50), new java.awt.Dimension(120, 50));
        helloUser = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        phoneNum = new javax.swing.JLabel();
        carrierList = new javax.swing.JComboBox();
        nextButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        canvas1 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocation(new java.awt.Point(500, 150));
        setMaximumSize(new java.awt.Dimension(475, 270));
        setMinimumSize(new java.awt.Dimension(475, 270));
        setPreferredSize(new java.awt.Dimension(380, 270));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helloUser.setFont(new java.awt.Font("Gurmukhi MT", 1, 36)); // NOI18N
        helloUser.setForeground(new java.awt.Color(255, 255, 255));
        helloUser.setText("WASUP");
        helloUser.setIconTextGap(5);
        helloUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                helloUserMouseMoved(evt);
            }
        });
        getContentPane().add(helloUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, 50));

        phoneNumberField.setBackground(new java.awt.Color(204, 204, 204));
        phoneNumberField.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        phoneNumberField.setPreferredSize(new java.awt.Dimension(85, 30));
        phoneNumberField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                phoneNumberFieldInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });
        getContentPane().add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, -1));

        phoneNum.setFont(new java.awt.Font("Gujarati Sangam MN", 0, 18)); // NOI18N
        phoneNum.setForeground(new java.awt.Color(255, 255, 255));
        phoneNum.setText("Enter Your Phone Number &  Carrier");
        phoneNum.setMaximumSize(new java.awt.Dimension(400, 24));
        phoneNum.setMinimumSize(new java.awt.Dimension(400, 24));
        phoneNum.setPreferredSize(new java.awt.Dimension(300, 24));
        getContentPane().add(phoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 310, 30));

        carrierList.setBackground(new java.awt.Color(153, 153, 153));
        carrierList.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        carrierList.setForeground(new java.awt.Color(255, 255, 255));
        carrierList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bell", "Fido", "Koodo", "Rogers", "Telus", "Virgin", "Wind" }));
        carrierList.setPreferredSize(new java.awt.Dimension(85, 30));
        carrierList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrierListActionPerformed(evt);
            }
        });
        getContentPane().add(carrierList, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 150, 80, -1));

        nextButton1.setBackground(new java.awt.Color(51, 51, 51));
        nextButton1.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        nextButton1.setForeground(new java.awt.Color(255, 255, 255));
        nextButton1.setText("Confirm");
        nextButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        nextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 80, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 160, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 470, -1));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 128, 92, 17));
        getContentPane().add(filler4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));
        getContentPane().add(filler6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        pack();
    }

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        // TODO add your handling code here:
        //AnimationClass action = new AnimationClass();
        //action.jLabelYDown(0,50,500,1,helloUser);
        String text = phoneNumberField.getText();
        int numDigit = text.length();
        carrier = (String)carrierList.getSelectedItem();
        email = null;
        
        //if(null != carrier)
        switch (carrier) {
            case "Koodo":
                email = text + "@msg.telus.com";
                break;
            case "Rogers":
                email = text + "@sms.rogers.com";
                break;
            case "Telus":
                email = text + "@msg.telus.com";
                break;
            case "Bell":
                email = text + "@txt.bellmobility.ca";
                break;
            case "Fido":
                email = text + "@sms.fido.ca";
                break;
            case "Virgin":
                email = text + "@vmobile.ca";
                break;
            case "Wind":
                email = text + "@txt.windmobile.ca";
                break;
            default:
                email = "Incorrect";
                break;
        }
        
        if(text.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter your number");
        }
        else if(numDigit < 10 || numDigit > 10)
        {
            JOptionPane.showMessageDialog(null,"Incorrect Number; please enter again");
        }
        else if (numDigit == 10)
        {
            JOptionPane.showMessageDialog(null, "Your Email is: " + email);
            try {
                new Matlab().startMatlab();
            } catch (MatlabInvocationException ex) {
                Logger.getLogger(IntroGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(IntroGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            this.setVisible(false);
            Matlab f = new Matlab ();
            f.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_nextButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox carrierList;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel helloUser;
    private javax.swing.JButton nextButton1;
    private javax.swing.JLabel phoneNum;
    private javax.swing.JTextField phoneNumberField;
    // End of variables declaration//GEN-END:variables

    private void elseIf(boolean equalsIgnoreCase) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
